PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS wallets (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	balance INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ledger (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	wallet_id INTEGER,
	amount INTEGER,
	type TEXT,
	reference TEXT UNIQUE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	stan TEXT,
	rrn TEXT,
	amount INTEGER,
	status TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(stan, rrn)
);
